source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
#inhibit_all_warnings!

def common
	pod 'WeexSDK'
	pod 'WeexPlugin', :git => 'https://github.com/kfeagle/WeexPlugin.git'
end

target 'WeexActionSheet' do
    common
end


